# This is only for Test
src=main.c init.c basic_shapes.c mouse_op.c board_print.c chess_op.c
para=-o main -Wall

main:$(src)
	gcc $(src) $(para)
clean:
	rm -rf main
	rm -rf *.o
	rm -rf ~*
run:
	./main
